### ISSUE TITLE
Maintenance & Lighthouse

### ISSUE THREAD

**Issue by ivanjeremic** [hindmost/cra-template-complex-browserext-typescript#1]
Hi I use this boilerplate currently to test things out and I must say it is the best boilerplate by far, are there any plans to maintain this boilerplate?

My second question would be since I'm using newTab in my extension and what the users see under newTab is a small React app, why does Google Lighthouse check not work correctly on this site? I wanted to check the new tab but got under performance only `?` ```First Contentful Paint
Error!
Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_NAVSTART)```

I know Lighthouse is not important for extensions however in case of complex newTab pages it would be nice to have basic checks, can it be that it is because of how react is working in this boilerplate? Thanks

**Comment by hindmost** [comment]
I will maintain this template, but only in order to keep it compatible with latest Create React App. And I have absolutely no intention of adding any features to it.
Regarding Lighthouse, it has no relation to this template. AFAIK Lighthouse is only applicable to HTTP(S) pages as well as chrome extension resources. So you can't audit the New tab directly. However, since you substitute it with your own page, you can audit the latter as any page within your extension. Such pages are accessible via: `chrome-extension://{EXTENSION_ID}/yourpage.html`.

BTW, you would star this template if it's really useful for you.
