### ISSUE TITLE
Missing types for extension library

### ISSUE THREAD

**Issue by ehartford** [hindmost/cra-template-complex-browserext-typescript#2]
How do i call things like:
* contextMenus
* storage
* declarativeContent
there are not typescript types?

**Comment by hindmost** [comment]
[webextension-polyfill](https://github.com/mozilla/webextension-polyfill#usage-with-typescript)

**Comment by ehartford** [comment]
I mean to say - that should be out of the box here, since it's a fundamental definition of browser extension.  It should be included in the template

**Comment by hindmost** [comment]
I don't think so. The only purpose of this template is setting up multiple Webpack entry points (that has no support in the original CRA). Furthermore it assumes as wide a usage as possible. `webextension-polyfill` doesn't support some specific APIs; also it doesn't support MV3. That's why it isn't included.
However you can always make you own template with your favourite features included.

**Comment by ehartford** [comment]
Understood.  Thank you for the excellent template, it has made life much easier for me.
